import 'dart:io';

/// Sets the app version to match the current git state.
///
/// The app's displayed "current version" is derived from the number of commits
/// in the repository (same scheme as the "latest version" pulled from GitHub),
/// so this script must be run before building a release:
///
///     dart run tool/update_version.dart
///
/// It updates:
///   - pubspec.yaml  - version: 1.0.0+[commit count] (read at runtime via
///                     package_info_plus, flows to Android/iOS/macOS/Windows)
///   - lib/core/build_info.dart - generated build info (for reference)
Future<void> main() async {
  final count = await _run('git', ['rev-list', '--count', 'HEAD']);
  final sha = await _run('git', ['rev-parse', '--short', 'HEAD']);
  if (count == null || sha == null) {
    stderr.writeln('error: not a git repository');
    exit(1);
  }

  final buildNumber = int.parse(count.trim());
  final version = _versionFromBuild(buildNumber);

  final pubspec = File('pubspec.yaml');
  final original = pubspec.readAsStringSync();
  final updated = original.replaceFirst(
    RegExp(r'^version:\s*.+$', multiLine: true),
    'version: 1.0.0+$buildNumber',
  );
  pubspec.writeAsStringSync(updated);

  final buildInfo = '''
/// Generated by tool/update_version.dart - do not edit manually.
class BuildInfo {
  /// git rev-list --count HEAD
  static const int commitCount = $buildNumber;

  /// git rev-parse --short HEAD
  static const String shortSha = '$sha';

  /// Human-readable version derived from the commit count.
  static const String version = '$version';
}
''';
  File('lib/core/build_info.dart').writeAsStringSync(buildInfo);

  stdout.writeln('version -> $version (1.0.0+$buildNumber, sha $sha)');
  stdout.writeln('pubspec.yaml updated, lib/core/build_info.dart written');
}

Future<String?> _run(String exe, List<String> args) async {
  try {
    final r = await Process.run(exe, args);
    return r.exitCode == 0 ? (r.stdout as String).trim() : null;
  } catch (_) {
    return null;
  }
}

String _versionFromBuild(int build) {
  final major = 1;
  final minor = build ~/ 100;
  final patch = build % 100;
  return '$major.$minor.$patch';
}
