/// Generated by tool/update_version.dart - do not edit manually.
class BuildInfo {
  /// git rev-list --count HEAD
  static const int commitCount = 16;

  /// git rev-parse --short HEAD
  static const String shortSha = '54b90c2';

  /// Human-readable version derived from the commit count.
  static const String version = '1.0.16';
}
